import type { CommunityFilterParams } from "@/lib/types";

export const APP_NAME = "RiftLite";

export const BRAND = {
  bgDark: "#0C1021",
  bgMid: "#101732",
  panel: "#141D3D",
  card: "#18244B",
  border: "#304A8A",
  gold: "#59A7FF",
  goldLight: "#84E7FF",
  goldDim: "#355AB1",
  text: "#EAF2FF",
  textDim: "#9FB3D9",
  win: "#49C187",
  loss: "#FF6B7A",
  accent: "#72D7FF",
  violet: "#A67CFF",
};

// Upper bound on the detailed public match window.
// Stored in chunked aggregate docs so /api/community/desktop can serve a
// larger window without one Firestore document becoming too large.
//
// Daily repair reads this many public match docs once.
// Normal freshness comes from desktop append calls; private hub totals use
// cached counters instead of hub-match scans.
//
// Match chunks are gzip+base64 packed before writing to Firestore.
// (see data.ts encodeMatches). Real-world ratio is roughly 6-8x because deck
// lists and field names repeat heavily, so 1,000-match chunks fit well
// under Firestore's 1 MB per-document cap.
export const COMMUNITY_WINDOW_SIZE = 7000;
export const COMMUNITY_CHUNK_SIZE = 1000;
export const DEFAULT_PAGE_SIZE = 25;
export const MAX_PAGE_SIZE = 100;
export const MATCH_CACHE_MS = 60_000;
export const TWITCH_STATUS_CACHE_MS = 60_000;
export const VENDETTA_PREVIEW_START_MS = Date.UTC(2026, 6, 6);
export const VENDETTA_LAUNCH_START_MS = Date.UTC(2026, 6, 31);

export const COMMUNITY_SEASONS = [
  {
    id: "vendetta-preview",
    label: "Vendetta Preview season",
    shortLabel: "Vendetta Preview",
    description: "Preview testing from 6 July 2026 until the set launches.",
  },
  {
    id: "vendetta-launch",
    label: "Vendetta launch season",
    shortLabel: "Vendetta Launch",
    description: "Official Vendetta season from 31 July 2026 onward.",
  },
  {
    id: "pre-vendetta",
    label: "Pre-Vendetta archive",
    shortLabel: "Pre-Vendetta",
    description: "The previous public meta before Vendetta previews started.",
  },
  {
    id: "",
    label: "All tracked seasons",
    shortLabel: "All seasons",
    description: "The full cached public community window.",
  },
] as const;
export const COMMUNITY_SEASON_IDS = COMMUNITY_SEASONS.map((season) => season.id);

export const SITE_PATHS = {
  home: "/",
  meta: "/community/meta",
  matrix: "/community/matrix",
  matches: "/community/matches",
  decks: "/community/decks",
  players: "/players",
  replays: "/replays",
  riftreplay: "/riftreplay",
  news: "/news",
  guide: "/guide",
  scorepad: "/scorepad",
  lfg: "/lfg",
  teams: "/teams",
  download: "/download",
  about: "/about",
  privacy: "/privacy",
  cookies: "/cookies",
};

export const DEFAULT_FILTERS: CommunityFilterParams = {
  range: "",
  season: "vendetta-preview",
  legend: "",
  result: "",
  seat: "",
  battlefield: "",
  flags: "",
  page: 1,
  pageSize: DEFAULT_PAGE_SIZE,
};

export const LEGENDS = [
  "Ahri",
  "Akali",
  "Ambessa",
  "Annie",
  "Azir",
  "Darius",
  "Diana",
  "Draven",
  "Ezreal",
  "Fiora",
  "Garen",
  "Irelia",
  "Ivern",
  "Jax",
  "Jhin",
  "Jinx",
  "Kai'Sa",
  "Kha'Zix",
  "Lee Sin",
  "LeBlanc",
  "Leona",
  "Lillia",
  "Lucian",
  "Lux",
  "Jayce",
  "Kennen",
  "Mel",
  "Master Yi",
  "Master Yi, Wuju Bladesman",
  "Master Yi, Wuju Master",
  "Miss Fortune",
  "Ornn",
  "Poppy",
  "Pyke",
  "Rek'Sai",
  "Renata Glasc",
  "Renekton",
  "Rengar",
  "Rumble",
  "Nasus",
  "Sett",
  "Shen",
  "Sivir",
  "Teemo",
  "Vex",
  "Vi",
  "Viktor",
  "Volibear",
  "Yasuo",
  "Zed",
] as const;

export const LEGEND_ALIASES = {
  victor: "Viktor",
  viktor: "Viktor",
  hiddenweapon: "Akali",
  fistofshadow: "Akali",
  unseenblade: "Akali",
  rogueassassin: "Akali",
  matriarchofwar: "Ambessa",
  chosenofthewolf: "Ambessa",
  defenderoftomorrow: "Jayce",
  defenderoftomorrows: "Jayce",
  heartofthetempest: "Kennen",
  newlyawakened: "Mel",
  soulsreflection: "Mel",
  aspectofthejackal: "Nasus",
  curatorsandsoftheburiedsun: "Nasus",
  curatorofthesands: "Nasus",
  butcherofthedesert: "Renekton",
  butcherofthesands: "Renekton",
  eyeoftwilight: "Shen",
  masterofshadows: "Zed",
  renata: "Renata Glasc",
  masteryi: "Master Yi",
  masteryiwujubladesman: "Master Yi, Wuju Bladesman",
  masteryiwujumaster: "Master Yi, Wuju Master",
  masteryiwujimaster: "Master Yi, Wuju Master",
  wujubladesman: "Master Yi, Wuju Bladesman",
  wujumaster: "Master Yi, Wuju Master",
  wujimaster: "Master Yi, Wuju Master",
  kaisa: "Kai'Sa",
  khazix: "Kha'Zix",
  reksai: "Rek'Sai",
  leblanc: "LeBlanc",
  missfortune: "Miss Fortune",
  mechanizedmenace: "Rumble",
  rocketbarrage: "Rumble",
  lilila: "Lillia",
} as const;

export const BATTLEFIELDS = [
  "Aspirant's Climb",
  "Altar to Unity",
  "Back-Alley Bar",
  "Bandle Tree",
  "Baron Pit",
  "Brush",
  "Emperor's Dais",
  "Forge of the Fluft",
  "Forgotten Monument",
  "Fortified Position",
  "Grove of the God-Willow",
  "Hall of Legends",
  "Hallowed Tomb",
  "Marai Spire",
  "Minefield",
  "Monastery of Hirana",
  "Navori Fighting Pit",
  "Obelisk of Power",
  "Ornn's Forge",
  "Piltovan Forge",
  "Power Nexus",
  "Ravenbloom Conservatory",
  "Reaver's Row",
  "Reckoner's Arena",
  "Rockfall Path",
  "Seat of Power",
  "Sigil of the Storm",
  "Sandswept Tomb",
  "Startipped Peak",
  "Sunken Temple",
  "Targon's Peak",
  "The Academy",
  "The Arena's Greatest",
  "The Candlelit Sanctum",
  "The Dreaming Tree",
  "The Grand Plaza",
  "The Papertree",
  "Treasure Hoard",
  "Trifarian War Camp",
  "Veiled Temple",
  "Vilemaw's Lair",
  "Void Gate",
  "Windswept Hillock",
  "Zaun Warrens",
  "Ancient Henge",
  "Dusk Rose Lab",
  "Dragon Roost",
  "Forbidding Waste",
  "Forgotten Library",
  "Frozen Fortress",
  "Gardens of Becoming",
  "Heisho, Shell of the World",
  "Kinkou Temple",
  "Mystic Vortex",
  "Abandoned Hall",
  "Amateur Recital",
  "Altar of Blood",
  "Black Flame Altar",
  "Protective Sands",
  "Risen Altar",
  "Ripper's Bay",
  "Shadow Temple",
  "Star Spring",
  "Threshold of the Gray",
  "Trapping Grounds",
  "Valley of Idols",
  "Vaults of Helia",
  "Catacombs of the Poros",
  "Frozen Vault",
  "Shadow Isles Ferry",
  "The Mage Seeker Vault",
  "Training Facility",
] as const;

export const BATTLEFIELD_ALIASES = {
  halloflegend: "Hall of Legends",
  ravensbloomconservatory: "Ravenbloom Conservatory",
  dreamingtree: "The Dreaming Tree",
  theacedemy: "The Academy",
  acedemy: "The Academy",
  academy: "The Academy",
  piltovanforge: "Piltovan Forge",
  piltoverforge: "Piltovan Forge",
  sandswepttomb: "Sandswept Tomb",
  thresholdofthegrey: "Threshold of the Gray",
  vaultofhelia: "Vaults of Helia",
} as const;
